-- Schema fixes for SQL Server after Phase 1 migration
-- Run these against the 'awx' database on SQL Server

-- Missing columns on main_instance (added by migration 0189)
ALTER TABLE main_instance ADD managed BIT NOT NULL DEFAULT 0;
ALTER TABLE main_instance ALTER COLUMN listener_port INT NULL;
ALTER TABLE main_instance ALTER COLUMN version NVARCHAR(255) NULL;

-- Missing job_created column on event tables
ALTER TABLE main_jobevent ADD job_created DATETIME2 NULL;
ALTER TABLE main_adhoccommandevent ADD job_created DATETIME2 NULL;
ALTER TABLE main_inventoryupdateevent ADD job_created DATETIME2 NULL;
ALTER TABLE main_projectupdateevent ADD job_created DATETIME2 NULL;
ALTER TABLE main_systemjobevent ADD job_created DATETIME2 NULL;

-- Missing main_receptoraddress table
CREATE TABLE main_receptoraddress (
    id INT IDENTITY(1,1) PRIMARY KEY,
    address NVARCHAR(255) NOT NULL,
    port INT NOT NULL,
    protocol NVARCHAR(10) NOT NULL DEFAULT 'tcp',
    websocket_path NVARCHAR(255) NOT NULL DEFAULT '',
    is_internal BIT NOT NULL DEFAULT 0,
    peers_from_control_nodes BIT NOT NULL DEFAULT 0,
    canonical BIT NOT NULL DEFAULT 0,
    created DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    modified DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    instance_id INT NOT NULL,
    CONSTRAINT fk_receptoraddress_instance FOREIGN KEY (instance_id) REFERENCES main_instance(id)
);

-- Missing M2M table for activity stream <-> receptor address
CREATE TABLE main_activitystream_receptor_address (
    id INT IDENTITY(1,1) PRIMARY KEY,
    activitystream_id INT NOT NULL,
    receptoraddress_id INT NOT NULL,
    CONSTRAINT fk_as_ra_activitystream FOREIGN KEY (activitystream_id) REFERENCES main_activitystream(id),
    CONSTRAINT fk_as_ra_receptoraddress FOREIGN KEY (receptoraddress_id) REFERENCES main_receptoraddress(id),
    CONSTRAINT uq_as_ra UNIQUE (activitystream_id, receptoraddress_id)
);

-- Unpartitioned views (required by AWX event queries)
IF NOT EXISTS (SELECT * FROM sys.views WHERE name = '_unpartitioned_main_jobevent')
    EXEC('CREATE VIEW _unpartitioned_main_jobevent AS SELECT * FROM main_jobevent');

IF NOT EXISTS (SELECT * FROM sys.views WHERE name = '_unpartitioned_main_inventoryupdateevent')
    EXEC('CREATE VIEW _unpartitioned_main_inventoryupdateevent AS SELECT * FROM main_inventoryupdateevent');

IF NOT EXISTS (SELECT * FROM sys.views WHERE name = '_unpartitioned_main_projectupdateevent')
    EXEC('CREATE VIEW _unpartitioned_main_projectupdateevent AS SELECT * FROM main_projectupdateevent');

IF NOT EXISTS (SELECT * FROM sys.views WHERE name = '_unpartitioned_main_adhoccommandevent')
    EXEC('CREATE VIEW _unpartitioned_main_adhoccommandevent AS SELECT * FROM main_adhoccommandevent');

IF NOT EXISTS (SELECT * FROM sys.views WHERE name = '_unpartitioned_main_systemjobevent')
    EXEC('CREATE VIEW _unpartitioned_main_systemjobevent AS SELECT * FROM main_systemjobevent');

-- Drop isjson CHECK constraints (auto-generated by mssql-django on JSONField columns)
DECLARE @sql NVARCHAR(MAX) = '';
SELECT @sql = @sql + 'ALTER TABLE [' + OBJECT_NAME(parent_object_id) + '] DROP CONSTRAINT [' + name + ']; '
FROM sys.check_constraints
WHERE definition LIKE '%isjson%';
IF @sql != '' EXEC sp_executesql @sql;
