-- Schema fixes for SQL Server after Gateway Django migrate
-- Run against the 'aap_gateway' database on SQL Server
-- ANSTRAT-1887 Phase 3: Gateway MSSQL Migration

USE aap_gateway;

-- Drop isjson CHECK constraints (auto-generated by mssql-django on JSONField columns)
-- These block valid JSON operations. Gateway JSONFields are in DAB tables:
--   dab_authentication_authenticator.configuration
--   dab_authentication_authenticatormap.map_type (if JSON)
--   dab_activitystream_entry.changes
--   dab_feature_flags_aapflag.labels
DECLARE @sql NVARCHAR(MAX) = '';
SELECT @sql = @sql + 'ALTER TABLE [' + OBJECT_NAME(parent_object_id) + '] DROP CONSTRAINT [' + name + ']; '
FROM sys.check_constraints
WHERE definition LIKE '%isjson%';
IF @sql != '' EXEC sp_executesql @sql;

-- Fix identity column reseed after data migration
-- Ensures new inserts get IDs above the migrated max
DECLARE @tbl NVARCHAR(200), @reseed_sql NVARCHAR(500);
DECLARE tbl_cursor CURSOR FOR
    SELECT t.name
    FROM sys.tables t
    JOIN sys.identity_columns ic ON t.object_id = ic.object_id
    WHERE t.is_ms_shipped = 0;

OPEN tbl_cursor;
FETCH NEXT FROM tbl_cursor INTO @tbl;
WHILE @@FETCH_STATUS = 0
BEGIN
    SET @reseed_sql = 'DBCC CHECKIDENT (''' + @tbl + ''', RESEED)';
    EXEC sp_executesql @reseed_sql;
    FETCH NEXT FROM tbl_cursor INTO @tbl;
END
CLOSE tbl_cursor;
DEALLOCATE tbl_cursor;
